/* Generated By:JavaCC: Do not edit this line. AutomataParserConstants.java */
package info3.game.automata.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AutomataParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONDITION = 5;
  /** RegularExpression Id. */
  int ACTION = 6;
  /** RegularExpression Id. */
  int SPECIAL_KEY = 7;
  /** RegularExpression Id. */
  int DIRVAR = 8;
  /** RegularExpression Id. */
  int ENTVAR = 9;
  /** RegularExpression Id. */
  int DIRECTION = 10;
  /** RegularExpression Id. */
  int CATEGORY = 11;
  /** RegularExpression Id. */
  int CAPITAL = 12;
  /** RegularExpression Id. */
  int LOWERCASE = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int UNARY = 16;
  /** RegularExpression Id. */
  int BINOP = 17;
  /** RegularExpression Id. */
  int ID = 18;
  /** RegularExpression Id. */
  int INT = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<CONDITION>",
    "<ACTION>",
    "<SPECIAL_KEY>",
    "\"d\"",
    "\"e\"",
    "<DIRECTION>",
    "<CATEGORY>",
    "<CAPITAL>",
    "<LOWERCASE>",
    "<LETTER>",
    "<DIGIT>",
    "\"!\"",
    "<BINOP>",
    "<ID>",
    "<INT>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\":\"",
    "\"?\"",
    "\"|\"",
    "\"Key(\"",
    "\"%\"",
    "\",\"",
  };

}
